# Generated by Django 6.0.2 on 2026-04-22 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20260421_1023'),
        ('quizzes', '0002_result_correct_answers_result_total_questions'),
    ]

    operations = [
    ]
